name: Xcode build iOS 15

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Xcode iOS build
      run: |
        cd Xcode/
        xcodebuild clean build -scheme TheNews -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0'
